config/routes.rb
Rails.application.routes.draw do
  resources :article_attachments
  mount Ckeditor::Engine => '/ckeditor'
  root 'articles#homepage'
  devise_for :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	mount_uploader :feature, FeatureUploader
	has_many :article_attachments
    accepts_nested_attributes_for :article_attachments
end

app/models/article_attachment.rb
class ArticleAttachment < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
    belongs_to :article
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_attachments_controller.rb
class ArticleAttachmentsController < ApplicationController
  before_action :set_article_attachment, only: [:show, :edit, :update, :destroy]

  # GET /article_attachments
  # GET /article_attachments.json
  def index
    @article_attachments = ArticleAttachment.all
  end

  # GET /article_attachments/1
  # GET /article_attachments/1.json
  def show
  end

  # GET /article_attachments/new
  def new
    @article_attachment = ArticleAttachment.new
  end

  # GET /article_attachments/1/edit
  def edit
  end

  # POST /article_attachments
  # POST /article_attachments.json
  def create
    @article_attachment = ArticleAttachment.new(article_attachment_params)

    respond_to do |format|
      if @article_attachment.save
        format.html { redirect_to @article_attachment, notice: 'Article attachment was successfully created.' }
        format.json { render :show, status: :created, location: @article_attachment }
      else
        format.html { render :new }
        format.json { render json: @article_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /article_attachments/1
  # PATCH/PUT /article_attachments/1.json
  def update
    respond_to do |format|
      if @article_attachment.update(article_attachment_params)
        format.html { redirect_to @article_attachment, notice: 'Article attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_attachment }
      else
        format.html { render :edit }
        format.json { render json: @article_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_attachments/1
  # DELETE /article_attachments/1.json
  def destroy
    @article_attachment.destroy
    respond_to do |format|
      format.html { redirect_to article_attachments_url, notice: 'Article attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_attachment
      @article_attachment = ArticleAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_attachment_params
      params.require(:article_attachment).permit(:article_id, :avatar)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_member!,only: [:edit, :update, :destroy, :new, :create]
	before_action :set_article,only: [:show, :edit, :update, :destroy]

	def index
		@articles=Article.order("created_at DESC")
		@article_attachments = @article.article_attachments.all
	end
	def homepage
		@articles=Article.order("created_at DESC").first(3)
		@article_attachments = @article.article_attachments.first(3)
	end
	def show
		
	end
	def new
		@article=Article.new
		@article_attachment = @article.article_attachments.build
	end
	def create
		@article=Article.new articles_params
		respond_to do |format|
     	if @article.save
       		params[:article_attachments]['avatar'].each do |a|
            @article_attachment = @article.article_attachments.create!(:avatar => a)
       		end
       		format.html { redirect_to @article, notice: 'Article was successfully created.' }
     	else
       		format.html { render action: 'new' }
     	end
   		end
		# if @article.save
		# 	params[:post_attachments]['avatar'].each do |a|
  #           @post_attachment = @post.post_attachments.create!(:avatar => a)
		#     redirect_to '/articles'
		# 	end
		# end
	end
	def edit
		
	end
	def update
		
		@article.update articles_params
		#update不用safe
		redirect_to articles_path
	end
	def destroy
		@article.destroy
		redirect_to articles_path
	end
	def articles_params
		params.require(:article).permit(:title,:date,:feature,:description,:body,post_attachments_attributes: [:id, :article_id, :avatar])
	end
	def set_article
		@article=Article.find params[:id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_attachments_helper.rb
module ArticleAttachmentsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/application/_navbar.html.erb
<% if current_member %>

      <%= link_to '登出',destroy_member_session_path, method: :delete,class: 'nav-item is-tab' %>

      <% else %>

      <%= link_to '登入',new_member_session_path,class: 'nav-item is-tab' %>

      <% end %> 

app/views/article_attachments/_form.html.erb
<%= form_with(model: article_attachment, local: true) do |form| %>
  <% if article_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article_attachment.errors.count, "error") %> prohibited this article_attachment from being saved:</h2>

      <ul>
      <% article_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :article_id %>
    <%= form.number_field :article_id %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.text_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/article_attachments/edit.html.erb
<h1>Editing Article Attachment</h1>

<%= render 'form', article_attachment: @article_attachment %>

<%= link_to 'Show', @article_attachment %> |
<%= link_to 'Back', article_attachments_path %>

app/views/article_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Article Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @article_attachments.each do |article_attachment| %>
      <tr>
        <td><%= article_attachment.article_id %></td>
        <td><%= article_attachment.avatar %></td>
        <td><%= link_to 'Show', article_attachment %></td>
        <td><%= link_to 'Edit', edit_article_attachment_path(article_attachment) %></td>
        <td><%= link_to 'Destroy', article_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article Attachment', new_article_attachment_path %>

app/views/article_attachments/new.html.erb
<h1>New Article Attachment</h1>

<%= render 'form', article_attachment: @article_attachment %>

<%= link_to 'Back', article_attachments_path %>

app/views/article_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @article_attachment.article_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @article_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_article_attachment_path(@article_attachment) %> |
<%= link_to 'Back', article_attachments_path %>

app/views/articles/_form.html.erb
   <%= form_for @article do |f| %>
       <!--  <div>
            <%= f.label :title,'標題' %>
              <div>
              <%= f.text_field :title,require: true, :cols => 30, :rows => 10 %>
              </div>
        </div> -->


        <div class="columns" >
          <div class="column is-10">
            <div class="field" >
            <%= f.label :title,'標題', class:'label' %>
              <div class="field" >
              <%= f.text_field :title,require: true %>
              </div>
            </div>
            <div class="field">
              <%= f.label :date,'日期', class:'label' %>
              <div class="control">
              <%= f.text_field :date,class:'input' %>
              </div>
            </div>
             <div class="field">
              <%= f.label :feature,'圖', class:'label' %>
              <div class="control">
              <%= f.file_field :feature,class:'input' %>
              </div>
            </div>
            <div class="field">
             <%= f.label :description,'簡短敘述', class:'label' %>
              <div class="control">
               <%= f.text_area :description,class:'textarea' %>
              </div>
            </div>
              <div class="field">
             <%= f.label :body,'文章內容', class:'label' %>
              <div class="control">
               <%= f.cktext_area :body,rows: 10 %>
              </div>
            </div>
            <div class="field">
            	<%= f.submit 'submit',class:'button is-primary is-medium is-fullwidth' %>
            </div>
          </div>
        </div>
      <% end %>

app/views/articles/edit.html.erb
<section class="section store-form-section">
  <div class="container">
    <h1 class="title is-4">更新文章</h1>
    <div class="box">
   <%= render 'form' %>
    </div>
  </div>
</section>

app/views/articles/homepage.html.erb
<% @articles.each do |article|%>
<div class="content">
    標題：<%= article.title %>
</div>
<div class="content">
    日期：<%= article.date %>
</div>
<div class="media-left">
	<figure>
		<%= image_tag article.feature_url.to_s %>
	</figure>

</div>
<div class="content has-description">
            
  <%= truncate article.description,length:150 %>
</div>
<div class="content has-description">
            
  <%=  raw article.body %>
</div>
<%=link_to edit_article_path(article),class:'button is-small is-primary is-outlined is-edit' do %>
	            <i class="fa fa-pencil-square-o">修改</i>
<% end %><br>
<%=link_to article_path(article) do %>
 <i class="fa fa-pencil-square-o">看完整</i>
<% end %>
<% if article != @articles.last %>
  <hr />
  <% end %> 
<% end %>

<%=link_to '/articles' do %>
 <i class="fa fa-pencil-square-o">看所有最新消息</i>
<% end %>

app/views/articles/index.html.erb
<% @articles.each do |article|%>
<div class="content">
    標題：<%= article.title %>
</div>
<div class="content">
    日期：<%= article.date %>
</div>
<div class="media-left">
  <figure>
    <%= image_tag article.feature_url.to_s %>
  </figure>

</div>
<div class="content has-description">
            
  <%= truncate article.description.html_safe,length:150 %>
</div>
<div class="content has-description">
            
  <%=  raw article.body %>
</div>
<%=link_to edit_article_path(article),class:'button is-small is-primary is-outlined is-edit' do %>
              <i class="fa fa-pencil-square-o">修改</i>
<% end %><br>
<%=link_to article_path(article) do %>
 <i class="fa fa-pencil-square-o">看完整</i>
<% end %>
<% if article != @articles.last %>
  <hr />
  <% end %> 
<% end %>
<%=link_to '/' do %>
 <i class="fa fa-pencil-square-o">回首頁</i>
<% end %>

app/views/articles/new.html.erb
    <h1 class="title is-4">新增文章</h1>
    <!-- <div class="box"> -->
	<%= render 'form' %>

 

app/views/articles/show.html.erb
 <div class="card">
          <div class="card-content">
            <div class="content">
                <p class="title is-4"><%= @article.title %></p>
            </div>
             <div class="content">
                <p class="title is-4"><%= @article.date %></p>
            </div>
         <div class="media-left">
                <figure class="image is-48x48">
                <%= image_tag @article.feature_url.to_s %>
                </figure>

          </div> 
            <div class="content has-description">
              <%= truncate @article.description,length:100 %>
            </div>
             <div class="content has-description">
            <%=  raw @article.body %>
            </div> 
           
          </div>
          <div class="card-footer">
            <div class="card-footer-item">
              <%= link_to 'edit',edit_article_path(@article) %>
            </div>
           <div class="card-footer-item">
              <%=link_to 'delete',article_path(@article),method: :delete,data:{confirm:'確定要刪除嗎？'} %>
            </div> 
          </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vote18</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>
    <%= yield %>
  </body>
</html>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>